apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
  name: airflow-datapipeline-scw-ingress
spec:
  rules:
    - host:  airflow.datapipeline.sa-scw.fr
      http:
        paths:
        - backend:
            service:
              name: airflow-webserver-service
              port:
                number: 8080
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - airflow.datapipeline.sa-scw.fr
      secretName: airflow-webserver-datapipeline-scw-tls