apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v --volumes persistentVolumeClaim --file docker-compose-compatible-kompose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: airflow-webserver
  name: airflow-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: airflow-webserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v --volumes persistentVolumeClaim --file docker-compose-compatible-kompose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: airflow-webserver
    spec:
      initContainers:
        - name: import-config
          image: alpine
          volumeMounts:
            - name: airflow-webserver-cm0
              mountPath: /configMap
            - name: airflow-webserver-init-claim
              mountPath: /sources
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              cp -rL /configMap/* /sources
              mkdir -p /sources/logs /sources/dags /sources/plugins
              chown -R 50000:0 /sources
          securityContext:
            runAsUser: 0
      containers:
        - image: rg.fr-par.scw.cloud/namespace-pipeline/airflow-scheduler:2.5
          args:
            - webserver
          env:
            - name: AIRFLOW_CONN_SPARK_CONNECTION
              value: spark://spark%3A%2F%2Fspark-master:7077
            - name: AIRFLOW__API__AUTH_BACKENDS
              value: airflow.api.auth.backend.basic_auth
            - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
              value: "true"
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__CORE__FERNET_KEY
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "false"
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://airflow:airflow@postgres/airflow"
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://airflow:airflow@postgres/airflow
            - name: _PIP_ADDITIONAL_REQUIREMENTS
#              value: apache_airflow==2.5.0 pyarrow==9.0.0 pyspark==3.1.3 markdown-it-py==2.1.0 mdit-py-plugins==0.3.1 marshmallow-oneofschema==3.0.1 lazy-object-proxy==1.8.0 jsonschema==4.17.3 Jinja2==3.1.2 itsdangerous==2.1.2 httpcore==0.16.2 gunicorn==20.1.0 httpx==0.23.1 dill==0.3.1.1 rich==12.6.0 cryptography==36.0.2 Werkzeug==2.2.2 croniter==1.3.8 Flask==2.2.2 apache-airflow-providers-apache-spark==4.1.0 pyOpenSSL==22.0.0
          name: airflow-webserver
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/airflow/dags
              name: airflow-webserver-cm0
            - mountPath: /opt/airflow/plugins
              name: airflow-webserver-claim2
            - mountPath: /usr/local/spark/app
              name: airflow-webserver-cm3
            - name: airflow-webserver-init-claim
              mountPath: /sources
      restartPolicy: Always
      volumes:
        - name: airflow-webserver-cm0
          configMap:
            name: airflow-webserver-cm0
        - name: airflow-webserver-claim2
          persistentVolumeClaim:
            claimName: airflow-webserver-claim2
        - name: airflow-webserver-cm3
          configMap:
            name: airflow-webserver-cm3
        - name: airflow-webserver-init-claim
          persistentVolumeClaim:
            claimName: airflow-webserver-init-claim