apiVersion: v1
data:
  core-site.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <!--
      Licensed to the Apache Software Foundation (ASF) under one or more
      contributor license agreements.  See the NOTICE file distributed with
      this work for additional information regarding copyright ownership.
      The ASF licenses this file to You under the Apache License, Version 2.0
      (the "License"); you may not use this file except in compliance with
      the License.  You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
    -->
    <configuration>
        <property>
            <name>fs.defaultFS</name>
            <value>hdfs://namenode:8020</value>
        </property>
        <property>
            <name>fs.default.name</name>
            <value>hdfs://namenode:8020</value>
        </property>
        <property>
            <name>hadoop.http.staticuser.user</name>
            <value>root</value>
        </property>
        <property>
            <name>hadoop.proxyuser.hue.hosts</name>
            <value>*</value>
        </property>
        <property>
            <name>hadoop.proxyuser.hue.groups</name>
            <value>*</value>
        </property>
    </configuration>
  hdfs-site.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <!--
      Licensed to the Apache Software Foundation (ASF) under one or more
      contributor license agreements.  See the NOTICE file distributed with
      this work for additional information regarding copyright ownership.
      The ASF licenses this file to You under the Apache License, Version 2.0
      (the "License"); you may not use this file except in compliance with
      the License.  You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
    -->
    <configuration>
        <property>
            <name>dfs.namenode.rpc-address</name>
            <value>namenode:8020</value>
        </property>
        <property>
            <name>dfs.replication</name>
            <value>1</value>
        </property>
        <property>
            <name>dfs.namenode.datanode.registration.ip-hostname-check</name>
            <value>false</value>
        </property>
        <property>
            <name>dfs.webhdfs.enabled</name>
            <value>true</value>
        </property>
        <property>
            <name>dfs.permissions.enabled</name>
            <value>false</value>
        </property>
    </configuration>
  hive.dockerfile: |-
    FROM apache/hive:3.1.3

    USER root

    RUN apt-get update && \
        apt-get install -y postgresql-client iputils-ping telnet lsof netcat

    COPY ./hivemetastore-site.xml /opt/hive/conf/hivemetastore-site.xml
    COPY ./hiveserver2-site.xml /opt/hive/conf/hiveserver2-site.xml
    COPY ./core-site.xml /opt/hive/conf/core-site.xml
    COPY ./hdfs-site.xml /opt/hive/conf/hdfs-site.xml
    COPY init-hive-db.sh /opt/hive/init/
    RUN chmod +x /opt/hive/init/init-hive-db.sh

    EXPOSE 9083 10000 10002
  hivemetastore-site.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <!--
      Licensed to the Apache Software Foundation (ASF) under one or more
      contributor license agreements.  See the NOTICE file distributed with
      this work for additional information regarding copyright ownership.
      The ASF licenses this file to You under the Apache License, Version 2.0
      (the "License"); you may not use this file except in compliance with
      the License.  You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
    -->
    <configuration>
        <property>
            <name>hive.server2.enable.doAs</name>
            <value>false</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionURL</name>
            <value>jdbc:postgresql://hive-postgres/metastore_db</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionDriverName</name>
            <value>org.postgresql.Driver</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionUserName</name>
            <value>hive</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionPassword</name>
            <value>password</value>
        </property>
        <property>
            <name>hive.tez.exec.inplace.progress</name>
            <value>false</value>
        </property>
        <property>
            <name>hive.exec.scratchdir</name>
            <value>/opt/hive/scratch_dir</value>
        </property>
        <property>
            <name>hive.user.install.directory</name>
            <value>/opt/hive/install_dir</value>
        </property>
        <property>
            <name>tez.runtime.optimize.local.fetch</name>
            <value>true</value>
        </property>
        <property>
            <name>hive.exec.submit.local.task.via.child</name>
            <value>false</value>
        </property>
        <property>
            <name>mapreduce.framework.name</name>
            <value>local</value>
        </property>
        <property>
            <name>tez.local.mode</name>
            <value>true</value>
        </property>
        <property>
            <name>hive.execution.engine</name>
            <value>tez</value>
        </property>
        <property>
            <name>hive.metastore.warehouse.dir</name>
            <value>/opt/hive/data/warehouse</value>
        </property>
        <property>
            <name>hive.exec.scratchdir</name>
            <value>/opt/hive/scratch_dir</value>
        </property>
        <property>
            <name>metastore.metastore.event.db.notification.api.auth</name>
            <value>false</value>
        </property>
    </configuration>
  hiveserver2-site.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <!--
      Licensed to the Apache Software Foundation (ASF) under one or more
      contributor license agreements.  See the NOTICE file distributed with
      this work for additional information regarding copyright ownership.
      The ASF licenses this file to You under the Apache License, Version 2.0
      (the "License"); you may not use this file except in compliance with
      the License.  You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
    -->
    <configuration>
        <property>
            <name>hive.server2.enable.doAs</name>
            <value>false</value>
        </property>
        <property>
            <name>hive.metastore.uris</name>
            <value>thrift://hive-metastore:9083</value>
        </property>
        <property>
        <name>hive.server2.thrift.bind.host</name>
        <value>0.0.0.0</value>
        </property>
        <property>
        <name>hive.server2.thrift.port</name>
        <value>10000</value>
        </property>
        <property>
            <name>hive.tez.exec.inplace.progress</name>
            <value>false</value>
        </property>
        <property>
            <name>hive.exec.scratchdir</name>
            <value>/opt/hive/scratch_dir</value>
        </property>
        <property>
            <name>hive.user.install.directory</name>
            <value>/opt/hive/install_dir</value>
        </property>
        <property>
            <name>tez.runtime.optimize.local.fetch</name>
            <value>true</value>
        </property>
        <property>
            <name>hive.exec.submit.local.task.via.child</name>
            <value>false</value>
        </property>
        <property>
            <name>mapreduce.framework.name</name>
            <value>local</value>
        </property>
        <property>
            <name>tez.local.mode</name>
            <value>true</value>
        </property>
        <property>
            <name>hive.execution.engine</name>
            <value>tez</value>
        </property>
        <property>
            <name>hive.metastore.warehouse.dir</name>
            <value>/opt/hive/data/warehouse</value>
        </property>
        <property>
            <name>metastore.metastore.event.db.notification.api.auth</name>
            <value>false</value>
        </property>
    </configuration>
  init-hive-db.sh: |-
    #!/bin/bash
    set -x

    : ${DB_DRIVER:=derby}

    SKIP_SCHEMA_INIT="${IS_RESUME:-false}"

    function initialize_hive {
      $HIVE_HOME/bin/schematool -dbType $DB_DRIVER -initSchema
      if [ $? -eq 0 ]; then
        echo "Initialized schema successfully.."
      else
        echo "Schema initialization failed!"
        exit 1
      fi
    }

    export HIVE_CONF_DIR=$HIVE_HOME/conf
    if [ -d "${HIVE_CUSTOM_CONF_DIR:-}" ]; then
      find "${HIVE_CUSTOM_CONF_DIR}" -type f -exec \
        ln -sfn {} "${HIVE_CONF_DIR}"/ \;
      export HADOOP_CONF_DIR=$HIVE_CONF_DIR
      export TEZ_CONF_DIR=$HIVE_CONF_DIR
    fi

    export HADOOP_CLIENT_OPTS="$HADOOP_CLIENT_OPTS -Xmx1G $SERVICE_OPTS"
    if [[ "${SKIP_SCHEMA_INIT}" == "false" ]]; then
      if hive --service schemaTool -info -dbType postgres | grep -q "Metastore schema version"; then
        echo "Hive Metastore schema is already initialized."
      else
        # Schema initialization
        echo "Initializing Hive Metastore database..."
        initialize_hive
      fi
    fi

    if [ "${SERVICE_NAME}" == "hiveserver2" ]; then
      export HADOOP_CLASSPATH=$TEZ_HOME/*:$TEZ_HOME/lib/*:$HADOOP_CLASSPATH
    elif [ "${SERVICE_NAME}" == "metastore" ]; then
      export METASTORE_PORT=${METASTORE_PORT:-9083}
    fi

    exec $HIVE_HOME/bin/hive --skiphadoopversion --skiphbasecp --service $SERVICE_NAME --hiveconf hive.root.logger=INFO,console
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: hive-metastore-cm0
