apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v --volumes persistentVolumeClaim --file docker-compose-compatible-kompose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: hive-postgres
  name: hive-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hive-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v --volumes persistentVolumeClaim --file docker-compose-compatible-kompose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: hive-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: metastore_db
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: hive
            - name: PGDATA
              value: /var/lib/postgresql/data/db-files/
          image: postgres:13
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - hive
                - -d
                - metastore_db
            failureThreshold: 5
            periodSeconds: 5
          name: hive-postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: hive-db-volume
          ports:
            - containerPort: 5432
              protocol: TCP
      hostname: hive-postgres
      restartPolicy: Always
      volumes:
        - name: hive-db-volume
          persistentVolumeClaim:
            claimName: hive-db-volume
