apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v --volumes persistentVolumeClaim --file docker-compose-compatible-kompose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: hive-metastore
  name: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hive-metastore
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v --volumes persistentVolumeClaim --file docker-compose-compatible-kompose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: hive-metastore
    spec:
      containers:
        - name: hive-metastore
{{/*          command:*/}}
{{/*            - "/bin/bash"*/}}
{{/*            - "-c"*/}}
{{/*            - |*/}}
{{/*              cd /opt/hive/conf*/}}
{{/*              mkdir -p /opt/hive/init/*/}}
{{/*              cp -L init-hive-db.sh /opt/hive/init/init-hive-db.sh*/}}
{{/*              chown -R 1000:1000 /opt/hive/init/init-hive-db.sh*/}}
{{/*              chmod +x /opt/hive/init/init-hive-db.sh*/}}
{{/*              cd /opt/hive/init*/}}
{{/*              /opt/hive/init/init-hive-db.sh*/}}
          args:
            - /opt/hive/init/init-hive-db.sh
          env:
            - name: DB_DRIVER
              value: postgres
            - name: SERVICE_NAME
              value: metastore
            - name: SERVICE_OPTS
              value: -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://hive-postgres:5432/metastore_db -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=password
          image: rg.fr-par.scw.cloud/namespace-pipeline/hive-server:latest
          livenessProbe:
            exec:
              command:
                - nc -zv localhost 9083
            failureThreshold: 5
            periodSeconds: 30
          ports:
            - containerPort: 9083
              protocol: TCP
          volumeMounts:
            - name: warehouse
              mountPath: /opt/hive/data/warehouse
{{/*            - name: hive-init*/}}
{{/*              mountPath: /opt/hive/conf*/}}
      securityContext:
        runAsUser: 0
      hostname: hive-metastore
      restartPolicy: Always
      volumes:
        - name: warehouse
          persistentVolumeClaim:
            claimName: warehouse
        - name: hive-init
          configMap:
            name: hive-metastore-cm0