apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v --volumes persistentVolumeClaim --file docker-compose-compatible-kompose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: namenode
  name: namenode
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: namenode
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v --volumes persistentVolumeClaim --file docker-compose-compatible-kompose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: namenode
    spec:
      initContainers:
        - name: init-format-namenode
          image: apache/hadoop:3
          command: [ 'sh', '-c', 'mkdir -p /hadoop/dfs/name && chown 1000:1000 /hadoop/dfs/name && chmod 777 -R /hadoop/dfs/name' ]
          volumeMounts:
            - name: namenode-claim0
              mountPath: /hadoop/dfs/name
          securityContext:
            runAsUser: 0
        - name: init-format-namenode2
          image: apache/hadoop:3
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - name: namenode-claim0
              mountPath: /hadoop/dfs/name
          env:
            - name: CORE-SITE.XML_fs.default.name
              value: hdfs://namenode
            - name: CORE-SITE.XML_fs.defaultFS
              value: hdfs://namenode
            - name: CORE-SITE.XML_hadoop.http.staticuser.user
              value: root
            - name: CORE-SITE.XML_hadoop.proxyuser.hue.groups
              value: '*'
            - name: CORE-SITE.XML_hadoop.proxyuser.hue.hosts
              value: '*'
            - name: ENSURE_NAMENODE_DIR
              value: /tmp/hadoop-root/dfs/name
            - name: HDFS-SITE.XML_dfs.datanode.name.dir
              value: file:///hadoop/dfs/data
            - name: HDFS-SITE.XML_dfs.namenode.datanode.registration.ip-hostname-check
              value: "false"
            - name: HDFS-SITE.XML_dfs.namenode.name.dir
              value: file:///hadoop/dfs/name
            - name: HDFS-SITE.XML_dfs.namenode.rpc-address
              value: namenode:8020
            - name: HDFS-SITE.XML_dfs.permissions.enabled
              value: "false"
            - name: HDFS-SITE.XML_dfs.replication
              value: "1"
            - name: HDFS-SITE.XNL_dfs.webhdfs.enabled
              value: "true"
            - name: YARN-SITE.XML_yarn.log-aggregation-enable
              value: "true"
            - name: YARN-SITE.XML_yarn.log_server_url
              value: http://historyserver:8188/applicationhistory/logs/
            - name: YARN-SITE.XML_yarn.nodemanager.remote-app-log-dir
              value: /app-logs
            - name: YARN-SITE.XML_yarn.resourcemanager.address
              value: resourcemanager:8032
            - name: YARN-SITE.XML_yarn.resourcemanager.fs.state-store.uri
              value: /rmstate
            - name: YARN-SITE.XML_yarn.resourcemanager.hostname
              value: resourcemanager
            - name: YARN-SITE.XML_yarn.resourcemanager.recovery.enabled
              value: "true"
            - name: YARN-SITE.XML_yarn.resourcemanager.resource-tracker.address
              value: resourcemanager:8031
            - name: YARN-SITE.XML_yarn.resourcemanager.scheduler.address
              value: resourcemanager:8030
            - name: YARN-SITE.XML_yarn.resourcemanager.store.class
              value: org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
            - name: YARN-SITE.XML_yarn.resourcemanager_system-metrics-publisher.enabled
              value: "true"
            - name: YARN-SITE.XML_yarn.timeline-service.enabled
              value: "true"
            - name: YARN-SITE.XML_yarn.timeline-service.generic-application-history.enabled
              value: "true"
            - name: YARN-SITE.XML_yarn.timeline-service.hostname
              value: historyserver
      containers:
        - args:
            - hdfs
            - namenode
          env:
            - name: CORE-SITE.XML_fs.default.name
              value: hdfs://namenode
            - name: CORE-SITE.XML_fs.defaultFS
              value: hdfs://namenode
            - name: CORE-SITE.XML_hadoop.http.staticuser.user
              value: root
            - name: CORE-SITE.XML_hadoop.proxyuser.hue.groups
              value: '*'
            - name: CORE-SITE.XML_hadoop.proxyuser.hue.hosts
              value: '*'
            - name: ENSURE_NAMENODE_DIR
              value: /hadoop/dfs/name
            - name: HDFS-SITE.XML_dfs.datanode.name.dir
              value: file:///hadoop/dfs/data
            - name: HDFS-SITE.XML_dfs.namenode.datanode.registration.ip-hostname-check
              value: "false"
            - name: HDFS-SITE.XML_dfs.namenode.name.dir
              value: file:///hadoop/dfs/name
            - name: HDFS-SITE.XML_dfs.namenode.rpc-address
              value: 0.0.0.0:8020
            - name: HDFS-SITE.XML_dfs.permissions.enabled
              value: "false"
            - name: HDFS-SITE.XML_dfs.replication
              value: "1"
            - name: HDFS-SITE.XNL_dfs.webhdfs.enabled
              value: "true"
            - name: YARN-SITE.XML_yarn.log-aggregation-enable
              value: "true"
            - name: YARN-SITE.XML_yarn.log_server_url
              value: http://historyserver:8188/applicationhistory/logs/
            - name: YARN-SITE.XML_yarn.nodemanager.remote-app-log-dir
              value: /app-logs
            - name: YARN-SITE.XML_yarn.resourcemanager.address
              value: resourcemanager:8032
            - name: YARN-SITE.XML_yarn.resourcemanager.fs.state-store.uri
              value: /rmstate
            - name: YARN-SITE.XML_yarn.resourcemanager.hostname
              value: resourcemanager
            - name: YARN-SITE.XML_yarn.resourcemanager.recovery.enabled
              value: "true"
            - name: YARN-SITE.XML_yarn.resourcemanager.resource-tracker.address
              value: resourcemanager:8031
            - name: YARN-SITE.XML_yarn.resourcemanager.scheduler.address
              value: resourcemanager:8030
            - name: YARN-SITE.XML_yarn.resourcemanager.store.class
              value: org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
            - name: YARN-SITE.XML_yarn.resourcemanager_system-metrics-publisher.enabled
              value: "true"
            - name: YARN-SITE.XML_yarn.timeline-service.enabled
              value: "true"
            - name: YARN-SITE.XML_yarn.timeline-service.generic-application-history.enabled
              value: "true"
            - name: YARN-SITE.XML_yarn.timeline-service.hostname
              value: historyserver
          image: apache/hadoop:3
          #command: ["hdfs", "namenode"]
          name: namenode
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - name: namenode-claim0
              mountPath: /hadoop/dfs/name
          ports:
            - containerPort: 9870
              protocol: TCP
            - containerPort: 8020
              protocol: TCP
      restartPolicy: Always
      volumes:
        - name: namenode-claim0
          persistentVolumeClaim:
            claimName: namenode-claim0