apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v --volumes persistentVolumeClaim --file docker-compose-compatible-kompose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: spark-worker
  name: spark-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v --volumes persistentVolumeClaim --file docker-compose-compatible-kompose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: spark-worker
    spec:
      containers:
        - args:
            - /opt/spark/bin/spark-class
            - org.apache.spark.deploy.worker.Worker
            - spark://spark-master:7077
          env:
            - name: SPARK_MASTER
              value: spark://spark-master:7077
            - name: SPARK_WORKER_DIR
              value: /tmp/spark
          image: apache/spark-py:v3.1.3
          name: spark-worker
          ports:
            - containerPort: 8081
              protocol: TCP
      hostname: spark-worker
      restartPolicy: Always
