apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
  name: spark-master-datapipeline-scw-ingress
spec:
  rules:
    - host:  spark-master.datapipeline.sa-scw.fr
      http:
        paths:
        - backend:
            service:
              name: spark-master
              port:
                number: 4040
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - spark-master.datapipeline.sa-scw.fr
      secretName: spark-master-datapipeline-scw-tls