apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v --volumes persistentVolumeClaim --file docker-compose-compatible-kompose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: spark-master
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-master
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v --volumes persistentVolumeClaim --file docker-compose-compatible-kompose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: spark-master
    spec:
      containers:
        - args:
            - /opt/spark/bin/spark-class
            - org.apache.spark.deploy.master.Master
          env:
            - name: SPARK_MASTER_HOST
              value: spark-master
            - name: SPARK_MASTER_PORT
              value: "7077"
          image: apache/spark-py:v3.1.3
          name: spark-master
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 7077
              protocol: TCP
            - containerPort: 6066
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/local/spark/app
              name: spark-master-cm0
      hostname: spark-master
      restartPolicy: Always
      volumes:
        - configMap:
            name: spark-master-cm0
          name: spark-master-cm0
