apiVersion: v1
data:
  metadata.yaml: |
    version: 1.0.0
    type: Database
    timestamp: '2023-08-18T20:29:07.663040+00:00'
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: superset-cm0-database-metadata
