apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
  name: zeppelin-datapipeline-scw-ingress
spec:
  rules:
    - host:  zeppelin.datapipeline.sa-scw.fr
      http:
        paths:
        - backend:
            service:
              name: zeppelin-service
              port:
                number: 2020
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - zeppelin.datapipeline.sa-scw.fr
      secretName: zeppelin-datapipeline-scw-tls